name: build-ui


on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
      - LTS-3-6
  pull_request_review:
    types: [submitted]
  # pull_request:
  #   branches: [main, master, LTS-3-6]
  #   types: [unlocked]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}


      - name: Build finish
        run : echo "Build Finished Successfully!"
