name: build-ui

on:
  pull_request:
    branches-ignore:
      - main
    types:
      - labeled

jobs:
  test:
    if: ${{ github.event.label.name == 'dependencies' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Test finish
        run : echo "Test Finished Successfully!"
